# Example config for launching OpenStack experiments.
---
# This specifies the curiosity method argument.
APPROACHES:
  glib_l2:
    NAME: "GLIB_L2"
    FLAGS:
      learning_name: LNDR
# Environments to run on.
ENVS:
  baking:
    NAME: "Baking"
ARGS: []
FLAGS: {}
START_SEED: 456
NUM_SEEDS: 1