
(define (domain bakingrealistic)
  (:requirements :typing)
  (:types powder_ingredient_hypothetical container butter_hypothetical measuring_cup oven dessert_hypothetical electric_stand_mixer egg_hypothetical mixture_hypothetical spatula)
  
  (:predicates (baking-powder-is-consumed ?v0 - powder_ingredient_hypothetical)
  	(is-spatula ?v0 - spatula)
  	(is-stand-mixer ?v0 - electric_stand_mixer)
	(butter-in-container ?v0 - container ?v1 - butter_hypothetical)
	(butter-in-measuring-cup ?v0 - butter_hypothetical ?v1 - measuring_cup)
	(butter-is-consumed ?v0 - butter_hypothetical)
	(container-in-an-oven ?v0 - container)
	(container-in-oven ?v0 - container ?v1 - oven)
	(cups-of-flour-is-consumed ?v0 - powder_ingredient_hypothetical)
	(dessert-in-container ?v0 - container ?v1 - dessert_hypothetical)
	(dessert-is-hypothetical ?v0 - dessert_hypothetical)
	(egg-in-container ?v0 - container ?v1 - egg_hypothetical)
	(egg-is-hypothetical ?v0 - egg_hypothetical)
	(is-baking-powder ?v0 - powder_ingredient_hypothetical)
	(is-bowl ?v0 - container)
	(is-butter ?v0 - butter_hypothetical)
	(is-cake ?v0 - dessert_hypothetical)
	(is-cups-of-flour ?v0 - powder_ingredient_hypothetical)
	(is-egg ?v0 - egg_hypothetical)
	(is-in-shell ?v0 - egg_hypothetical)
	(is-mixture ?v0 - mixture_hypothetical)
	(is-oven ?v0 - oven)
	(is-pan ?v0 - container)
	(is-plate ?v0 - container)
	(is-raw-egg-whites ?v0 - egg_hypothetical)
	(is-raw-egg-yolk ?v0 - egg_hypothetical)
	(is-souffle ?v0 - dessert_hypothetical)
	(is-sugar ?v0 - powder_ingredient_hypothetical)
	(is-tablespoons-of-flour ?v0 - powder_ingredient_hypothetical)
	(is-whipped-egg-whites ?v0 - egg_hypothetical)
	(is-whole-raw-egg ?v0 - egg_hypothetical)
	(mixture-has-baking-powder ?v0 - mixture_hypothetical)
	(mixture-has-blended-raw-egg-whites ?v0 - mixture_hypothetical)
	(mixture-has-butter ?v0 - mixture_hypothetical)
	(mixture-has-cups-of-flour ?v0 - mixture_hypothetical)
	(mixture-has-folded-raw-egg-whites ?v0 - mixture_hypothetical)
	(mixture-has-raw-egg-yolk ?v0 - mixture_hypothetical)
	(mixture-has-sugar ?v0 - mixture_hypothetical)
	(mixture-has-tablespoons-of-flour ?v0 - mixture_hypothetical)
	(mixture-in-container ?v0 - container ?v1 - mixture_hypothetical)
	(mixture-is-airy ?v0 - mixture_hypothetical)
	(mixture-is-hypothetical ?v0 - mixture_hypothetical)
	(oven-is-full ?v0 - oven)
	(oven-is-heated-for-cake ?v0 - oven)
	(oven-is-heated-for-souffle ?v0 - oven)
	(pan-is-damaged ?v0 - container)
	(pan-is-full ?v0 - container)
	(powder-ingredient-in-container ?v0 - container ?v1 - powder_ingredient_hypothetical)
	(powder-ingredient-in-measuring-cup ?v0 - powder_ingredient_hypothetical ?v1 - measuring_cup)
	(sugar-is-consumed ?v0 - powder_ingredient_hypothetical)
	(tablespoons-of-flour-is-consumed ?v0 - powder_ingredient_hypothetical)
	(beat-egg-whites ?v0 - electric_stand_mixer ?v1 - container ?v2 - egg_hypothetical)
	(crack-egg-and-put-in-container ?v0 - egg_hypothetical ?v1 - container)
	(fold-stiff-egg-whites-into-mixture ?v0 - spatula ?v1 - container ?v2 - container ?v3 - egg_hypothetical ?v4 - mixture_hypothetical)
	(move-baked-good-in-container-to-different-container ?v0 - container ?v1 - container ?v2 - dessert_hypothetical)
	(pour-mixture-only ?v0 - container ?v1 - container ?v2 - mixture_hypothetical)
	(pour-powdery-ingredient-from-container ?v0 - container ?v1 - container ?v2 - powder_ingredient_hypothetical)
	(pour-powdery-ingredient-from-measuring-cup ?v0 - powder_ingredient_hypothetical ?v1 - measuring_cup ?v2 - container)
	(preheat-oven-with-cake-settings ?v0 - oven)
	(preheat-oven-with-souffle-settings ?v0 - oven)
	(put-butter-in-container-from-measuring-cup ?v0 - butter_hypothetical ?v1 - container)
	(put-pan-in-oven ?v0 - container ?v1 - oven)
	(remove-pan-from-oven ?v0 - container ?v1 - oven)
	(separate-raw-yolk-from-egg-whites ?v0 - egg_hypothetical ?v1 - egg_hypothetical ?v2 - container ?v3 - container)
	(set-oven-with-cake-bake-time-and-press-start ?v0 - oven ?v1 - dessert_hypothetical ?v2 - mixture_hypothetical)
	(set-oven-with-souffle-bake-time-and-press-start ?v0 - oven ?v1 - dessert_hypothetical ?v2 - mixture_hypothetical)
	(transfer-butter-from-pan-or-bowl ?v0 - container ?v1 - container ?v2 - butter_hypothetical)
	(transfer-egg-from-pan-or-bowl ?v0 - container ?v1 - container ?v2 - egg_hypothetical)
	(use-stand-mixer ?v0 - electric_stand_mixer ?v1 - container ?v2 - mixture_hypothetical)
		(different ?arg0 - powder_ingredient_hypothetical ?arg1 - powder_ingredient_hypothetical)
		(different ?arg0 - container ?arg1 - container)
		(different ?arg0 - butter_hypothetical ?arg1 - butter_hypothetical)
		(different ?arg0 - measuring_cup ?arg1 - measuring_cup)
		(different ?arg0 - oven ?arg1 - oven)
		(different ?arg0 - dessert_hypothetical ?arg1 - dessert_hypothetical)
		(different ?arg0 - egg_hypothetical ?arg1 - egg_hypothetical)
		(different ?arg0 - mixture_hypothetical ?arg1 - mixture_hypothetical)
		(different ?arg0 - spatula ?arg1 - spatula)
	
  )
  ; (:actions set-oven-with-cake-bake-time-and-press-start separate-raw-yolk-from-egg-whites pour-powdery-ingredient-from-measuring-cup pour-powdery-ingredient-from-container transfer-butter-from-pan-or-bowl beat-egg-whites preheat-oven-with-cake-settings put-butter-in-container-from-measuring-cup move-baked-good-in-container-to-different-container put-pan-in-oven crack-egg-and-put-in-container pour-mixture-only set-oven-with-souffle-bake-time-and-press-start preheat-oven-with-souffle-settings fold-stiff-egg-whites-into-mixture use-stand-mixer transfer-egg-from-pan-or-bowl remove-pan-from-oven)

  

	(:action bake-cake
		:parameters (?x0 - mixture_hypothetical ?x1 - dessert_hypothetical ?x2 - oven ?x3 - container)
		:precondition (and (oven-is-heated-for-cake ?x2)
			(set-oven-with-cake-bake-time-and-press-start ?x2 ?x1 ?x0)
			(dessert-is-hypothetical ?x1)
			(not (mixture-is-hypothetical ?x0))
			(container-in-oven ?x3 ?x2)
			(not (pan-is-full ?x3))
			(is-pan ?x3)
			(mixture-in-container ?x3 ?x0)
			(mixture-has-blended-raw-egg-whites ?x0)
			(mixture-has-raw-egg-yolk ?x0)
			(mixture-has-butter ?x0)
			(mixture-has-sugar ?x0)
			(mixture-has-cups-of-flour ?x0)
			(mixture-has-baking-powder ?x0)
			(not (mixture-is-airy ?x0)))
		:effect (and
			(not (is-mixture ?x0))
			(not (mixture-has-blended-raw-egg-whites ?x0))
			(not (mixture-has-raw-egg-yolk ?x0))
			(not (mixture-has-butter ?x0))
			(not (mixture-has-sugar ?x0))
			(not (mixture-has-cups-of-flour ?x0))
			(not (mixture-has-baking-powder ?x0))
			(not (mixture-in-container ?x3 ?x0))
			(not (dessert-is-hypothetical ?x1))
			(is-cake ?x1)
			(pan-is-full ?x3)
			(dessert-in-container ?x3 ?x1))
	)
	

	(:action bake-souffle
		:parameters (?x0 - mixture_hypothetical ?x1 - dessert_hypothetical ?x2 - oven ?x3 - container)
		:precondition (and (oven-is-heated-for-souffle ?x2)
			(set-oven-with-souffle-bake-time-and-press-start ?x2 ?x1 ?x0)
			(dessert-is-hypothetical ?x1)
			(is-mixture ?x0)
			(is-pan ?x3)
			(not (pan-is-full ?x3))
			(mixture-in-container ?x3 ?x0)
			(container-in-oven ?x3 ?x2)
			(not (mixture-is-hypothetical ?x0))
			(mixture-has-folded-raw-egg-whites ?x0)
			(mixture-has-raw-egg-yolk ?x0)
			(mixture-has-butter ?x0)
			(mixture-has-sugar ?x0)
			(not (mixture-has-cups-of-flour ?x0))
			(mixture-is-airy ?x0))
		:effect (and
			(not (is-mixture ?x0))
			(not (mixture-has-folded-raw-egg-whites ?x0))
			(not (mixture-has-raw-egg-yolk ?x0))
			(not (mixture-has-butter ?x0))
			(not (mixture-has-sugar ?x0))
			(not (mixture-has-tablespoons-of-flour ?x0))
			(not (mixture-is-airy ?x0))
			(not (mixture-in-container ?x3 ?x0))
			(not (dessert-is-hypothetical ?x1))
			(is-souffle ?x1)
			(pan-is-full ?x3)
			(dessert-in-container ?x3 ?x1))
	)
	

	(:action beat-egg-whites
		:parameters (?x0 - electric_stand_mixer ?x1 - container ?x2 - egg_hypothetical)
		:precondition (and (egg-in-container ?x1 ?x2)
			(beat-egg-whites ?x0 ?x1 ?x2)
			(is-raw-egg-whites ?x2)
			(is-egg ?x2)
			(not (egg-is-hypothetical ?x2)))
		:effect (and
			(is-whipped-egg-whites ?x2))
	)
	

	(:action crack-egg-in-container
		:parameters (?x0 - container ?x1 - egg_hypothetical)
		:precondition (and (not (egg-in-container ?x0 ?x1))
			(crack-egg-and-put-in-container ?x1 ?x0)
			(is-egg ?x1)
			(is-in-shell ?x1)
			(not (container-in-an-oven ?x0)))
		:effect (and
			(egg-in-container ?x0 ?x1)
			(is-whole-raw-egg ?x1)
			(not (is-in-shell ?x1)))
	)
	

	(:action fold-egg-whites-into-mixture
		:parameters (?x0 - spatula ?x1 - mixture_hypothetical ?x2 - container ?x3 - container ?x4 - egg_hypothetical)
		:precondition (and (mixture-in-container ?x2 ?x1)
			(fold-stiff-egg-whites-into-mixture ?x0 ?x3 ?x2 ?x4 ?x1)
			(egg-in-container ?x3 ?x4)
			(is-whipped-egg-whites ?x4)
			(not (egg-is-hypothetical ?x4))
			(is-mixture ?x1)
			(not (mixture-is-hypothetical ?x1))
			(not (container-in-an-oven ?x3))
			(not (container-in-an-oven ?x2)))
		:effect (and
			(mixture-is-airy ?x1)
			(not (is-whipped-egg-whites ?x4))
			(not (is-raw-egg-whites ?x4))
			(not (is-egg ?x4))
			(mixture-has-folded-raw-egg-whites ?x1)
			(not (egg-in-container ?x3 ?x4)))
	)
	

	(:action place-dessert-on-plate
		:parameters (?x0 - dessert_hypothetical ?x1 - container ?x2 - container)
		:precondition (and (dessert-in-container ?x2 ?x0)
			(move-baked-good-in-container-to-different-container ?x2 ?x1 ?x0)
			(not (dessert-is-hypothetical ?x0))
			(is-plate ?x1)
			(not (container-in-an-oven ?x1))
			(not (container-in-an-oven ?x2)))
		:effect (and
			(dessert-in-container ?x1 ?x0)
			(not (pan-is-full ?x2))
			(not (dessert-in-container ?x2 ?x0)))
	)
	

	(:action preheat-for-cake
		:parameters (?x0 - oven)
		:precondition (and (preheat-oven-with-cake-settings ?x0)
			(not (oven-is-heated-for-cake ?x0)))
		:effect (and
			(oven-is-heated-for-cake ?x0)
			(not (oven-is-heated-for-souffle ?x0)))
	)
	

	(:action preheat-for-souffle
		:parameters (?x0 - oven)
		:precondition (and (preheat-oven-with-souffle-settings ?x0)
			(not (oven-is-heated-for-souffle ?x0)))
		:effect (and
			(not (oven-is-heated-for-cake ?x0))
			(oven-is-heated-for-souffle ?x0))
	)
	

	(:action put-butter-in-container
		:parameters (?x0 - measuring_cup ?x1 - butter_hypothetical ?x2 - container)
		:precondition (and (is-butter ?x1)
			(put-butter-in-container-from-measuring-cup ?x1 ?x2)
			(not (butter-in-container ?x2 ?x1))
			(not (container-in-an-oven ?x2))
			(butter-in-measuring-cup ?x1 ?x0))
		:effect (and
			(butter-in-container ?x2 ?x1)
			(not (butter-in-measuring-cup ?x1 ?x0)))
	)
	

	(:action put-pan-in-oven
		:parameters (?x0 - oven ?x1 - container)
		:precondition (and (is-pan ?x1)
			(put-pan-in-oven ?x1 ?x0)
			(not (container-in-an-oven ?x1))
			(not (oven-is-full ?x0)))
		:effect (and
			(container-in-oven ?x1 ?x0)
			(container-in-an-oven ?x1)
			(oven-is-full ?x0))
	)
	

	(:action put-powdery-ingredient-in-container
		:parameters (?x0 - measuring_cup ?x1 - container ?x2 - powder_ingredient_hypothetical)
		:precondition (and (not (powder-ingredient-in-container ?x1 ?x2))
			(pour-powdery-ingredient-from-measuring-cup ?x2 ?x0 ?x1)
			(not (container-in-an-oven ?x1))
			(powder-ingredient-in-measuring-cup ?x2 ?x0))
		:effect (and
			(powder-ingredient-in-container ?x1 ?x2)
			(not (powder-ingredient-in-measuring-cup ?x2 ?x0)))
	)
	

	(:action put-powdery-ingredient-into-container
		:parameters (?x0 - measuring_cup ?x1 - container ?x2 - powder_ingredient_hypothetical)
		:precondition (and (not (powder-ingredient-in-container ?x1 ?x2))
			(pour-powdery-ingredient-from-measuring-cup ?x2 ?x0 ?x1)
			(not (container-in-an-oven ?x1))
			(powder-ingredient-in-measuring-cup ?x2 ?x0))
		:effect (and
			(powder-ingredient-in-container ?x1 ?x2)
			(not (powder-ingredient-in-measuring-cup ?x2 ?x0)))
	)
	

	(:action remove-pan-from-oven
		:parameters (?x0 - oven ?x1 - container)
		:precondition (and (container-in-oven ?x1 ?x0)
			(remove-pan-from-oven ?x1 ?x0)
			(oven-is-full ?x0)
			(is-pan ?x1))
		:effect (and
			(not (oven-is-full ?x0))
			(not (container-in-oven ?x1 ?x0))
			(not (container-in-an-oven ?x1))
			(not (oven-is-heated-for-cake ?x0))
			(not (oven-is-heated-for-souffle ?x0)))
	)
	

	(:action separate-egg
		:parameters (?x0 - egg_hypothetical ?x1 - container ?x2 - container ?x3 - egg_hypothetical)
		:precondition (and (is-egg ?x3)
			(separate-raw-yolk-from-egg-whites ?x3 ?x0 ?x1 ?x2)
			(not (container-in-an-oven ?x1))
			(not (container-in-an-oven ?x2))
			(is-whole-raw-egg ?x3)
			(not (is-in-shell ?x3))
			(not (is-egg ?x0))
			(egg-is-hypothetical ?x0)
			(egg-in-container ?x1 ?x3))
		:effect (and
			(not (egg-is-hypothetical ?x0))
			(not (is-whole-raw-egg ?x3))
			(is-egg ?x0)
			(is-raw-egg-yolk ?x3)
			(is-raw-egg-whites ?x0)
			(egg-in-container ?x2 ?x0))
	)
	

	(:action transfer-butter
		:parameters (?x0 - butter_hypothetical ?x1 - container ?x2 - container)
		:precondition (and (butter-in-container ?x2 ?x0)
			(transfer-butter-from-pan-or-bowl ?x2 ?x1 ?x0)
			(is-butter ?x0)
			(not (container-in-an-oven ?x2))
			(not (container-in-an-oven ?x1)))
		:effect (and
			(not (butter-in-container ?x2 ?x0))
			(butter-in-container ?x1 ?x0))
	)
	

	(:action transfer-egg
		:parameters (?x0 - egg_hypothetical ?x1 - container ?x2 - container)
		:precondition (and (egg-in-container ?x2 ?x0)
			(transfer-egg-from-pan-or-bowl ?x2 ?x1 ?x0)
			(not (egg-is-hypothetical ?x0))
			(is-egg ?x0)
			(not (container-in-an-oven ?x2))
			(not (container-in-an-oven ?x1)))
		:effect (and
			(not (egg-in-container ?x2 ?x0))
			(egg-in-container ?x1 ?x0))
	)
	

	(:action transfer-mixture
		:parameters (?x0 - mixture_hypothetical ?x1 - container ?x2 - container)
		:precondition (and (mixture-in-container ?x2 ?x0)
			(pour-mixture-only ?x2 ?x1 ?x0)
			(not (mixture-is-hypothetical ?x0))
			(is-mixture ?x0)
			(not (container-in-an-oven ?x2))
			(not (container-in-an-oven ?x1))
			(not (pan-is-full ?x1)))
		:effect (and
			(not (mixture-in-container ?x2 ?x0))
			(mixture-in-container ?x1 ?x0))
	)
	

	(:action transfer-powdery-ingredient
		:parameters (?x0 - powder_ingredient_hypothetical ?x1 - container ?x2 - container)
		:precondition (and (powder-ingredient-in-container ?x2 ?x0)
			(pour-powdery-ingredient-from-container ?x2 ?x1 ?x0)
			(not (container-in-an-oven ?x2))
			(not (container-in-an-oven ?x1)))
		:effect (and
			(not (powder-ingredient-in-container ?x2 ?x0))
			(powder-ingredient-in-container ?x1 ?x0))
	)
	
	(:action use-stand-mixer-in-bowl-with-mixture-set1-baking-powder-butter-cups-of-flour-sugar-whole-raw-egg
		:parameters (?x0 - mixture_hypothetical ?x1 - butter_hypothetical ?x2 - egg_hypothetical ?x3 - container ?x4 - powder_ingredient_hypothetical ?x5 - powder_ingredient_hypothetical ?x6 - powder_ingredient_hypothetical ?x7 - electric_stand_mixer)
		:precondition (and (use-stand-mixer ?x7 ?x3 ?x0)
			(is-stand-mixer ?x7)
			(is-bowl ?x3)
			(mixture-is-hypothetical ?x0)
			(butter-in-container ?x3 ?x1)
			(egg-in-container ?x3 ?x2)
			(is-baking-powder ?x5)
			(is-butter ?x1)
			(is-cups-of-flour ?x4)
			(is-sugar ?x6)
			(is-whole-raw-egg ?x2)
			(powder-ingredient-in-container ?x3 ?x5)
			(powder-ingredient-in-container ?x3 ?x4)
			(powder-ingredient-in-container ?x3 ?x6))
		:effect (and
			(mixture-in-container ?x3 ?x0)
			(is-mixture ?x0)
			(not (mixture-is-hypothetical ?x0))
			(mixture-has-baking-powder ?x0)
			(mixture-has-butter ?x0)
			(mixture-has-cups-of-flour ?x0)
			(mixture-has-sugar ?x0)
			(mixture-has-raw-egg-yolk ?x0)
			(mixture-has-blended-raw-egg-whites ?x0)
			(not (butter-in-container ?x3 ?x1))
			(not (egg-in-container ?x3 ?x2))
			(not (is-egg ?x2))
			(not (is-baking-powder ?x5))
			(not (is-butter ?x1))
			(not (is-cups-of-flour ?x4))
			(not (is-sugar ?x6))
			(not (is-whole-raw-egg ?x2))
			(not (powder-ingredient-in-container ?x3 ?x5))
			(not (powder-ingredient-in-container ?x3 ?x4))
			(not (powder-ingredient-in-container ?x3 ?x6)))
	)


	(:action use-stand-mixer-in-bowl-with-mixture-set1-butter-raw-egg-yolk-sugar-tablespoons-of-flour
		:parameters (?x0 - mixture_hypothetical ?x1 - powder_ingredient_hypothetical ?x2 - electric_stand_mixer ?x3 - butter_hypothetical ?x4 - egg_hypothetical ?x5 - container ?x6 - powder_ingredient_hypothetical)
		:precondition (and (use-stand-mixer ?x2 ?x5 ?x0)
			(is-stand-mixer ?x2)
			(is-bowl ?x5)
			(mixture-is-hypothetical ?x0)
			(butter-in-container ?x5 ?x3)
			(egg-in-container ?x5 ?x4)
			(is-butter ?x3)
			(is-raw-egg-yolk ?x4)
			(is-sugar ?x1)
			(is-tablespoons-of-flour ?x6)
			(powder-ingredient-in-container ?x5 ?x1)
			(powder-ingredient-in-container ?x5 ?x6))
		:effect (and
			(mixture-in-container ?x5 ?x0)
			(is-mixture ?x0)
			(not (mixture-is-hypothetical ?x0))
			(mixture-has-butter ?x0)
			(mixture-has-raw-egg-yolk ?x0)
			(mixture-has-sugar ?x0)
			(mixture-has-tablespoons-of-flour ?x0)
			(not (butter-in-container ?x5 ?x3))
			(not (egg-in-container ?x5 ?x4))
			(not (is-butter ?x3))
			(not (is-raw-egg-yolk ?x4))
			(not (is-egg ?x4))
			(not (is-sugar ?x1))
			(not (is-tablespoons-of-flour ?x6))
			(not (powder-ingredient-in-container ?x5 ?x1))
			(not (powder-ingredient-in-container ?x5 ?x6)))
	)

  

)
        